version: "3.7"

services:
  minio:
    image: "minio/minio"
    command: server -C /etc/minio --address ":9000" --console-address ":9001" /data
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - minio:/data

volumes:
  minio:
    name: minio-${NAME}
