version: "3.7"

services:
  keycloak:
    container_name: ${NAME}-keycloak
    image: quay.io/keycloak/keycloak:19.0.0
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./realm-export.json:/tmp/realm-export.json:ro
      - ../target/${POM_ARTIFACT_ID}-jar-with-dependencies.jar:/opt/keycloak/providers/${POM_ARTIFACT_ID}.jar:ro
    entrypoint:
      - sh
      - -c
      - |
        /opt/keycloak/bin/kc.sh build
        IMPORT_FLAG_FILE=/opt/keycloak/imported.flag
        if [ "$${KEYCLOAK_IMPORT}" != "" ]; then
          if [ ! -f "$$IMPORT_FLAG_FILE" ]; then
            /opt/keycloak/bin/kc.sh import --file "$$KEYCLOAK_IMPORT"
            touch "$$IMPORT_FLAG_FILE"
          fi
        fi
        /opt/keycloak/bin/kc.sh start-dev
    environment:
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      ACCOUNT_AVATAR_S3_ENDPOINT: "http://minio:9000"
      ACCOUNT_AVATAR_S3_ACCESS_KEY: admin
      ACCOUNT_AVATAR_S3_SECRET_KEY: P@ssw0rd
      ACCOUNT_AVATAR_S3_BUCKET_NAME: account-avatar
      ACCOUNT_AVATAR_S3_PREFIX: ""
      ACCOUNT_AVATAR_S3_REGION: us-east-1
      # KC_DB_URL: jdbc:postgresql://postgres:5432/postgres?ssl=allow
      # KC_DB_USERNAME: postgres
      # KC_DB_PASSWORD: postgres
      # KC_DB: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: P@ssw0rd
  #   postgres:
  #     image: postgres:12
  #     container_name: ${NAME}-postgres
  #     restart: always
  #     ports:
  #       - 5432:5432
  #     environment:
  #       POSTGRES_DATABASE: postgres
  #       POSTGRES_PASSWORD: postgres
  #       POSTGRES_USER: postgres
  #     volumes:
  #       - postgres:/var/lib/postgresql/data

  minio:
    image: "minio/minio"
    command: server -C /etc/minio --address ":9000" --console-address ":9001" /data
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - minio:/data

volumes:
  minio:
    name: minio-${NAME}
#   postgres:
#     name: postgres-${NAME}
